import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { getPayments } from "@/lib/api";
import { formatDate, formatMoney } from "@/lib/format";

export default async function PaymentsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const params = await searchParams; const query = new URLSearchParams();
  if (params.source) query.set("source", params.source); if (params.status) query.set("status", params.status); if (params.method) query.set("method", params.method); if (params.search) query.set("search", params.search); query.set("limit", "100");
  const data = await getPayments(query.toString());
  return <><PageHeader eyebrow="TRANSACTIONS" title="Payments" description="Search and inspect payment attempts, methods, status, source, and failure context."/><form className="mt-6 grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-[1fr_150px_160px_160px_auto]"><input className="rounded-lg border border-slate-200 px-3 py-2 text-sm" defaultValue={params.search} name="search" placeholder="Payment, order, or customer"/><select className="rounded-lg border border-slate-200 px-3 py-2 text-sm" defaultValue={params.source ?? "all"} name="source"><option value="all">All sources</option><option value="demo">Demo</option><option value="razorpay">Razorpay</option></select><select className="rounded-lg border border-slate-200 px-3 py-2 text-sm" defaultValue={params.status ?? ""} name="status"><option value="">All statuses</option>{["captured","failed","authorized","refunded"].map(v=><option key={v}>{v}</option>)}</select><select className="rounded-lg border border-slate-200 px-3 py-2 text-sm" defaultValue={params.method ?? ""} name="method"><option value="">All methods</option>{["upi","card","netbanking","wallet"].map(v=><option key={v}>{v}</option>)}</select><button className="rounded-lg bg-brand px-5 py-2 text-sm font-semibold text-white">Apply</button></form><div className="mt-5 overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-card"><div className="border-b border-slate-100 px-5 py-4 text-sm text-slate-500">Showing {data.items.length} of {data.total} payments</div><table className="w-full min-w-[1080px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{["Payment / order","Customer","Source","Amount","Method","Status","Created","Error"].map(h=><th className="px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{data.items.map(p=><tr className={p.status === "failed" ? "bg-rose-50/30" : ""} key={p.id}><td className="px-4 py-3"><p className="font-medium">{p.external_payment_id}</p><p className="text-xs text-slate-400">{p.external_order_id}</p></td><td className="px-4 py-3">{p.customer_name}</td><td className="px-4 py-3 capitalize">{p.source}</td><td className="px-4 py-3 font-semibold">{formatMoney(p.amount)}</td><td className="px-4 py-3 capitalize">{p.method}</td><td className="px-4 py-3"><StatusBadge value={p.status}/></td><td className="px-4 py-3 text-slate-500">{formatDate(p.created_at)}</td><td className="max-w-64 px-4 py-3 text-xs text-rose-700">{p.error_code ? <><p className="font-semibold">{p.error_code}</p><p className="mt-1">{p.error_description}</p></> : "—"}</td></tr>)}</tbody></table></div></>;
}
